---
title: "test"
output: html_document
date: "2023-05-12"
---

# Testdokument

## Including Plots

You can also embed plots, for example:

```{  r}
plot(pressure)
```

## Thema

- Liste
- Liste
- Liste

Gleichung: $e^{i\pi} = -1$

1. abc
2. def
3. ghi


```{r} 
2+4
```


```{r}
data <- cars[1:4, ]
knitr::kable(data, caption = "Tabelle")
```

<details>
Dies ist ein versteckter Textbaustein.
</details> 

### Unterthema 

- Liste
- Liste

Gleichung: $e^{i\pi} = -1$

1. abc
2. def
3. ghi

#### Unterunterthema

- Liste
- Liste

Gleichung: $e^{i\pi} = -1$

1. abc
2. def
3. ghi

## Zweites Thema

<details>
```{r}
7*3
```
</details> 

```{r echo=FALSE}
dat <- data.frame("Spalte 1" = c(1,2,3,4), "Spalte 2" = c(5,6,7,8))
plot(dat)
```

```{r eval=FALSE}
17+34
```
## Erstes Thema

```{r}
#|eval: false
plot(c(1,2,3,4))
```


## Zweites Thema

<details>
```{r eval=FALSE}
dat <- data.frame("Spalte 1" = c(4,3,2,1), "Spalte 2" = c(5,6,7,8))
plot(dat)
```
</details> 

```{r include=FALSE}
dat <- data.frame("Spalte 1" = c(1,2,3,4), "Spalte 2" = c(5,6,7,8))
plot(dat)
```


