---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Fehler 


## Aufgabe 1

Welcher Fehler tritt im folgenden Code auf? Korrigiere ihn und führe den Code aus. 

```{r}

library(ggplot)

```


```{r}
# Hier kannst du deine Lösung ausprobieren.


```

<!-- loesung: start-->
<details>
```{r}

library(ggplot2)

```
</details>
<!-- loesung: ende-->



## Aufgabe 2

Welcher Fehler tritt im folgenden Code auf? Korrigiere ihn und führe den Code aus. 

```{r}

x <- 10
y <- "5"
result <- x + y

```


```{r}
# Hier kannst du deine Lösung ausprobieren.


```

<!-- loesung: start-->
<details>
```{r}

x <- 10
y <- 5  # y wurde als Text gespeichert und Berechnungen können nicht auf Text angewendet werden

# alternativ kann Text (character) auch in eine Zahl (numeric) umgewandelt werden: 
y <- as.numeric(y) 

result <- x + y

```
</details>
<!-- loesung: ende-->


## Aufgabe 3

Welcher Fehler tritt im folgenden Code auf? Korrigiere ihn und führe den Code aus. 

```{r}

vek <- c(10, 20, 30, 40, 50)
vec[4,2]

```


```{r}
# Hier kannst du deine Lösung ausprobieren.


```

<!-- loesung: start-->
<details>
```{r}

vec <- c(10, 20, 30, 40, 50)
vec[c(4,2)] 

```
</details>
<!-- loesung: ende-->
