
# Logische Operatoren 


## Aufgabe 1

Erstelle ein Objekt `x` mit dem Wert $5000$ und ein Objekt `y` mit dem Wert $8^4$. Prüfe, ob $x > y$. 

```{r}
# Hier kannst du deine Lösung ausprobieren.


```

<!-- loesung: start-->
<details>
```{r}

x <- 5000
y <- 8^4
x > y

```
</details>
<!-- loesung: ende-->


## Aufgabe 2

Erstelle einen Vektor `z` mit den Werten $0.5, 0.75, 0.25, 1, 1.25, 1.5$. Prüfe, welche Werte kleiner oder gleich eins ($<= 1$) sind. 

```{r}
# Hier kannst du deine Lösung ausprobieren.


```

<!-- loesung: start-->
<details>
```{r}

z <- c(0.5, 0.75, 0.25, 1, 1.25, 1.5)
z <= 1

```
</details>
<!-- loesung: ende-->


## Aufgabe 3

Erstelle einen Vektor `v` mit den Werten $5,3,4,5,5,7,2$. Ändere den zweiten Wert in eine $5$. Speichere alle Werte mit einer $5$ aus dem Vektor `v` in einem neuen Vektor `w`.

```{r}
# Hier kannst du deine Lösung ausprobieren.


```

<!-- loesung: start-->
<details>
```{r}

v <- c(5,3,4,5,5,7,2)
v[2] <- 5
w <- v[v == 5]

```
</details>
<!-- loesung: ende-->
