name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Set up conda environment
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: rtraining
        environment-file: environment.yml
    - name: Initialize conda
      run: |
        conda init bash
    # set up R - Kernel
    - name: R Kernel
      shell: bash -el {0} # need to restart bash; apparently this may do the trick
      run: |
        conda activate rtraining
        Rscript -e "IRkernel::installspec()"
    # translate Rmd to myst
    - name: R Kernel
      shell: bash -el {0} # need to restart bash; apparently this may do the trick
      run: |
        conda activate rtraining
        Rscript Aufgaben_rmd/rmd2myst.R
    # Build the book
    - name: Build the book
      shell: bash -el {0}
      run: |
        conda activate rtraining
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
