# https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token
name: Docker Image For Dependencies

on:
  pull_request:
    branches:
      main
  
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Check if environment changed
        id: file_changes 
        run: |
          if git diff --quiet HEAD origin/main -- environment.yml; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - name: Build Docker with Dependencies
        run: |
          if [[ "${{ steps.git-diff.outputs.changed }}" == "true" ]]; then
            ls && docker build . --file .github/workflows/Dockerfile --tag ghcr.io/methods-berlin/rtraining_dep:latest
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
            docker push ghcr.io/methods-berlin/rtraining_dep:latest
          else
            echo "File has not changed. Skipping docker build."
          fi

  
