# https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token
name: Docker Image For Dependencies

on:
  pull_request:
    branches:
      main
  
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Build Docker with Dependencies
        run: |
          # We check if the environment.yml file changed when compared to main:          
          git fetch                         # fetch branches
          if git diff --exit-code HEAD main -- environment.yml; then
            # if there is a change, we update the docker image
            ls && docker build . --file .github/workflows/Dockerfile --tag ghcr.io/methods-berlin/rtraining_dep:latest
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
            docker push ghcr.io/methods-berlin/rtraining_dep:latest
          else
            echo "File has not changed. Skipping docker build."
          fi
  

  
